//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNuocHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVotes
    {
        public int Id { get; set; }
        public string user_id { get; set; }
        public Nullable<double> avg_rating { get; set; }
        public Nullable<int> vote_count { get; set; }
    }
}
